# Generated by Django 5.0.4 on 2024-06-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_pay',
            new_name='amount_paid',
        ),
    ]
